#!/usr/bin/env python3
"""
TestID Map Generator
Generate markdown report from captured testids
"""

import sys
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List


def generate_testid_map(captured_data: Dict, output_file: Path) -> Dict:
    """
    Generate markdown testid map from captured data

    Args:
        captured_data: Dict with structure from testid_extractor
        output_file: Path to write markdown file

    Returns:
        Result dict with status and file path
    """

    markdown_lines = [
        "# TestID Map — customers-manager-ui",
        "",
        f"**Last updated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "> This file is the **single source of truth** for selectors in E2E tests.",
        "> Auto-generated by `/testid-extractor` — do not edit manually.",
        "",
        "## Table of Contents",
        ""
    ]

    # Add TOC
    for page_name in captured_data.get("pages", {}).keys():
        anchor = page_name.lower().replace(" ", "-")
        markdown_lines.append(f"- [{page_name}](#{anchor})")

    markdown_lines.extend(["", "---", ""])

    # Add content for each page
    for page_name, page_data in captured_data.get("pages", {}).items():
        anchor = page_name.lower().replace(" ", "-")
        markdown_lines.extend([
            f"## {page_name}",
            "",
            f"**Path**: `{page_data.get('path', 'unknown')}`",
            "",
            f"**Testids captured**: {len(page_data.get('testids', []))}",
            ""
        ])

        testids = page_data.get("testids", [])
        if testids:
            markdown_lines.extend([
                "### Selectors",
                "",
                "| Component | TestID | Selector | Type |",
                "|-----------|--------|----------|------|",
            ])

            for testid in sorted(testids):
                selector = f'`[data-testid="{testid}"]`'
                testid_display = f'`{testid}`'
                testid_type = _classify_testid(testid)
                markdown_lines.append(f"| - | {testid_display} | {selector} | {testid_type} |")

            markdown_lines.append("")

        # Add tree if available
        if page_data.get("tree"):
            markdown_lines.extend([
                "### Tree Structure",
                "",
                "```",
                _format_tree(page_data["tree"]),
                "```",
                ""
            ])

        markdown_lines.extend(["---", ""])

    # Add summary
    total_testids = sum(len(p.get("testids", [])) for p in captured_data.get("pages", {}).values())
    total_pages = len(captured_data.get("pages", {}))

    markdown_lines.extend([
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Pages | {total_pages} |",
        f"| Total Testids | {total_testids} |",
        f"| Last Updated | {datetime.now().isoformat()} |",
        "",
        "> **Usage**: Copy selector from this map and use in E2E tests.",
        "> Example: `page.locator('[data-testid=\"a3b9f1c204\"]').click()`",
        ""
    ])

    # Write file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(markdown_lines))

    return {
        "status": "success",
        "file": str(output_file),
        "lines": len(markdown_lines),
        "pages": total_pages,
        "testids": total_testids
    }


def _classify_testid(testid: str) -> str:
    """Classify testid by pattern"""
    if "-col-" in testid and "-row-" in testid:
        return "table-cell"
    elif "-col-" in testid:
        return "table-col"
    elif "-row-" in testid and ("-button-" in testid or "-input-" in testid or "-select-" in testid):
        return "table-row-interactive"
    elif "-row-" in testid:
        return "table-row"
    elif "-item-" in testid and ("-button-" in testid or "-input-" in testid):
        return "item-interactive"
    elif "-item-" in testid:
        return "list-item"
    elif any(tag in testid for tag in ["-button-", "-input-", "-select-", "-a-", "-div-", "-span-"]):
        return "interactive"
    else:
        return "root"


def _format_tree(tree: Dict, indent: int = 0) -> str:
    """Format tree structure as ASCII art"""
    lines = []
    items = sorted(tree.items())

    for i, (key, value) in enumerate(items):
        is_last = i == len(items) - 1
        prefix = "└── " if is_last else "├── "
        lines.append("  " * indent + prefix + key)

        if isinstance(value, dict):
            sub_tree = _format_tree(value, indent + 1)
            lines.append(sub_tree)

    return "\n".join(lines)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate testid map")
    parser.add_argument("--input", required=True, help="Input captured data JSON")
    parser.add_argument("--output", help="Output markdown file")

    args = parser.parse_args()

    input_file = Path(args.input)
    if not input_file.exists():
        print(f"Error: Input file {input_file} not found", file=sys.stderr)
        return 1

    with open(input_file, "r") as f:
        captured_data = json.load(f)

    output_file = Path(args.output) if args.output else Path("docs/testid-map.md")

    result = generate_testid_map(captured_data, output_file)
    print(json.dumps(result, indent=2))

    return 0


if __name__ == "__main__":
    sys.exit(main())
